### ISSUE TITLE
Thanks for adding this! Leaving some screenshots here

### ISSUE THREAD

**Issue by fnune** [edunfelt/base16-rose-pine-scheme#2]
This just popped up on https://github.com/fnune/base16-vim

Thanks for adding it! Leaving some screenshots here in case you want to use them.

`rose-pine-moon`
![image](https://user-images.githubusercontent.com/16181067/111915967-113fc580-8a79-11eb-972c-2cb38b404bd6.png)

`rose-pine`
![image](https://user-images.githubusercontent.com/16181067/111915992-35030b80-8a79-11eb-96d0-768ded57db37.png)

`rose-pine-dawn`
![image](https://user-images.githubusercontent.com/16181067/111916002-45b38180-8a79-11eb-96b1-4eb96ef04117.png)

**Comment by edunfelt** [comment]
That's awesome, thank you! I'll add them to the readme.
