### ISSUE TITLE
It seems the base08 color is not in accordance with other base16 themes

### ISSUE THREAD

**Issue by italovieira** [edunfelt/base16-rose-pine-scheme#3]
I'm using base16 themes for my window manager appearance. When using the rose-pine dark variation, it seems the base08 color is white, very light. I was comparing with other base16 colors and all of them use a red color for base08.

**Comment by edunfelt** [comment]
Thanks for noticing! I will try to look over the colors in the coming days.

**Comment by edunfelt** [comment]
Hi again @italovieira!

I hope the latest commit made the theme more consistent with other base16 themes. Feel free to open another issue or @ me here if it still doesn't look right.

Closing for now.

// Emilia
