### ISSUE TITLE
rose-pine-moon has base08 defined twice

### ISSUE THREAD

**Issue by belak** [edunfelt/base16-rose-pine-scheme#4]
I just noticed that we had an error in our [CI for base16-emacs](https://github.com/tinted-theming/base16-emacs/actions/runs/5565157943/jobs/10165297716) after the [rose-pine schemes were updated](https://github.com/tinted-theming/base16-schemes/commit/4e7f93270e4642b8a5eb8b170db209c5887e056f). 
```
base08: "ecebf0"
base08: "eb6f92"
```
I'm not sure which one is correct, but I'm going with `eb6f92` to fix our copy of this [here](https://github.com/tinted-theming/base16-schemes/commit/4e7f93270e4642b8a5eb8b170db209c5887e056f). If it should be something different, I'll switch it when this repo is updated.

**Comment by edunfelt** [comment]
I also had a build fail tonight -- thank you for spotting this!

Indeed, it should be `eb6f92`. Fixed in https://github.com/edunfelt/base16-rose-pine-scheme/commit/4161952824f4ede6c3eb73ef6b5f3609a76cf69a.
